---
cec_api_enabled: false
dnscrypt_proxy_allowed_ips: ""
dnscrypt_proxy_allowed_names: ""
dnscrypt_proxy_blocked_ips: ""
dnscrypt_proxy_blocked_names: ""
dnscrypt_proxy_enabled: false
gazpar2haws_enabled: false
gazpar2haws_grdf_username: "{{vault_gazpar2haws_grdf_username}}"
gazpar2haws_grdf_password: "{{vault_gazpar2haws_grdf_password}}"
gazpar2haws_grdf_pce_identifier: "{{vault_gazpar2haws_grdf_pce_identifier}}"
gazpar2haws_ha_token: "{{vault_gazpar2haws_ha_token}}"
homeassistant_enabled: false
homeserver_admin_password: "{{vault_homeserver_admin_password}}"
homeserver_admin_user: "admin"
homeserver_root_dir: "/home/apps"
homeserver_timezone: "Europe/Paris"
minidlna_enabled: false
minidlna_media_dirs: "/media"
rf433_api_enabled: false
samba_enabled: false
samba_shares: ""
sickgear_downloads_dir: "./downloads"
sickgear_enabled: false
sickgear_tv_dir: "./tv"
transmission_downloads_dir: "./downloads"
transmission_enabled: false
tvheadend_enabled: false
tvheadend_recordings_dir: "./recordings"
watchtower_cleanup: "true"
watchtower_enabled: false
watchtower_notification_url: ""
watchtower_rolling_restart: "true"
watchtower_schedule: "0 0 3 * * 0"
watchtower_timeout: "60s"
