---
calicoctl_version: "3.30.5"
calicoctl_checksum: "sha256:6cdfb17b0276f648f4fdb051a5d75617a50b3c328d4cccfc40d087b96c361d80"
cmctl_version: "2.4.0"
cmctl_checksum: "sha256:57d12fc2c5fd7a9f2df372130c7da7f995855a06058ca41a2b6c66c26a6ca7ae"
containers_storage_dir: "/home/apps/containers/storage"
etcd_version: "3.6.5"
etcd_checksum: "sha256:66bad39ed920f6fc15fd74adcb8bfd38ba9a6412f8c7852d09eb11670e88cac3"
helm_version: "3.19.4"
helm_checksum: "sha256:759c656fbd9c11e6a47784ecbeac6ad1eb16a9e76d202e51163ab78504848862"
k8s_cert_hash: ""
k8s_cert_key: ""
k8s_master_host: "{{inventory_hostname}}"
k8s_master_port: "6443"
k8s_node_labels: "kubernetes-host="
k8s_node_name: "{{inventory_hostname_short}}"
k8s_node_role: ""
k8s_node_taints: ""
k8s_pod_cidr: "10.244.0.0/16"
k8s_service_cidr: "10.96.0.0/12"
k8s_join_token: ""
k8s_registry_auths: "{{vault_k8s_registry_auths}}"
k8s_version: "1.34.3"
k8s_version_minor: "1.34"
k9s_version: "0.50.16"
k9s_checksum: "sha256:bda09dc030a08987fe2b3bed678b15b52f23d6705e872d561932d4ca07db7818"
kubectx_version: "0.9.5"
kubectx_checksum: "sha256:e887e4e2b3dd4c94d0ecdb84270fb4fac2e65c4d5b0ee461e688fb8089fd4900"
kubens_version: "0.9.5"
kubens_checksum: "sha256:509c97c0882e688ae8fad8aa13524cc7c003e4883db447a905bdb47d64c13bdc"
skip_modprobe: false
skip_services: false
skip_sysctl: false
